### ISSUE TITLE
it sounds very great, but please describe how i use?

### ISSUE THREAD

**Issue by Nader-GenKO** [DavidXanatos/IgnoreACLs#1]
Actually, it sounds very great (ignore ACLs), what is the instructions for using it please? also, is this will help me copy/replace files in WindowsApps folder?

**Comment by Fadexz** [comment]
I basically have the same question.
Seems like the instructions are very simplified though and assume you know how to do each step

**Comment by DavidXanatos** [comment]
Usage:

    Enable test signing mode on your PC

    Install using the ini file

    run: fltmc load IgnoreACLsDriver

    run: fltmc attach IgnoreACLsDriver c:

    do whatever you want

    run: fltmc detach IgnoreACLsDriver c:

    run: fltmc unload IgnoreACLsDriver

**Comment by Fadexz** [comment]
Thanks for responding, I did read that as mentioned but I assume I just run those in cmd when cd into it, not sure what you would do at the "do whatever you want" part.

**Comment by DavidXanatos** [comment]
"do whatever you want" that is where you do what you wanted to do but the ACLs prevented you from doing, mess with your system, access protected filed, delete windows deffender, etc etc, whatever....
once you are done and want to re enable the enforcement of ACLs you continue with the next fltmc command

**Comment by Fadexz** [comment]
Thanks, that makes a lot more sense, appreciate it  :)

**Comment by DavidXanatos** [comment]
ok i have updated the readme.md to be more explicite
